export const INIT_READINGSVOLUMES = "INIT_READINGSVOLUMES";
export const REFRESH_READINGSVOLUMES = "REFRESH_READINGSVOLUMES";

export const INIT_COLLECTIONS = "INIT_COLLECTIONS";
export const REFRESH_COLLECTIONS = "REFRESH_COLLECTIONS";
